'use client'

import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Check, ChevronRight, Edit3, FileDown, IndianRupee, Menu, MessageCircle, Plus, ReceiptText, Sparkles, Trash2, X } from 'lucide-react'

type PaymentMethod = 'Cash' | 'Online'
type Receipt = { id: string; receiptNo: string; houseNo: string; amount: number; paymentMethod: PaymentMethod; date: string }
type FormState = { receiptNo: string; houseNo: string; amount: string; paymentMethod: PaymentMethod; date: string }

const STORAGE_KEY = 'receiptly-receipts'
const GANESH_IMAGE = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-08-16%20at%207.17.43%20PM-4XxX7fKWMzPhks0uj7hRUfdmZSLuFy.jpeg'
const today = () => new Date().toISOString().slice(0, 10)
const formatMoney = (value: number) => `Rs. ${value.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`
const formatDate = (value: string) => new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`))
function blankForm(nextReceiptNo: string): FormState { return { receiptNo: nextReceiptNo, houseNo: '', amount: '', paymentMethod: 'Cash', date: today() } }

export default function Page() {
  const [receipts, setReceipts] = useState<Receipt[]>([])
  const [form, setForm] = useState<FormState>(() => blankForm('001'))
  const [errors, setErrors] = useState<Partial<Record<keyof FormState, string>>>({})
  const [selectedReceipt, setSelectedReceipt] = useState<Receipt | null>(null)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [hydrated, setHydrated] = useState(false)

  useEffect(() => { try { const stored = window.localStorage.getItem(STORAGE_KEY); if (stored) setReceipts(JSON.parse(stored)) } catch { setReceipts([]) } setHydrated(true) }, [])
  useEffect(() => { if (hydrated) window.localStorage.setItem(STORAGE_KEY, JSON.stringify(receipts)) }, [receipts, hydrated])

  const totals = useMemo(() => { const todayReceipts = receipts.filter((receipt) => receipt.date === today()); return { today: todayReceipts.reduce((sum, receipt) => sum + receipt.amount, 0), total: receipts.reduce((sum, receipt) => sum + receipt.amount, 0), count: receipts.length, todayCount: todayReceipts.length } }, [receipts])
  function updateField(field: keyof FormState, value: string) { setForm((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: undefined })) }
  function validate() { const next: typeof errors = {}; if (!form.receiptNo.trim()) next.receiptNo = 'Add a receipt number.'; if (!form.houseNo.trim()) next.houseNo = 'Add a house or customer number.'; if (!form.amount || Number(form.amount) <= 0) next.amount = 'Enter an amount greater than zero.'; if (!form.date) next.date = 'Choose a date.'; setErrors(next); return Object.keys(next).length === 0 }
  function saveReceipt(event: React.FormEvent) { event.preventDefault(); if (!validate()) return; const data = { receiptNo: form.receiptNo.trim(), houseNo: form.houseNo.trim(), amount: Number(form.amount), paymentMethod: form.paymentMethod, date: form.date }; if (editingId) { const updated = { id: editingId, ...data }; setReceipts((current) => current.map((receipt) => receipt.id === editingId ? updated : receipt)); setSelectedReceipt(updated); setEditingId(null) } else { const receipt = { id: crypto.randomUUID(), ...data }; setReceipts((current) => [receipt, ...current]); setSelectedReceipt(receipt) }; setForm(blankForm(String(Math.max(0, ...receipts.map((receipt) => Number(receipt.receiptNo) || 0), Number(form.receiptNo) || 0) + 1).padStart(3, '0'))) }
  function editReceipt(receipt: Receipt) { setSelectedReceipt(null); setEditingId(receipt.id); setForm({ receiptNo: receipt.receiptNo, houseNo: receipt.houseNo, amount: String(receipt.amount), paymentMethod: receipt.paymentMethod, date: receipt.date }); document.getElementById('new-receipt')?.scrollIntoView({ behavior: 'smooth', block: 'center' }) }
  function deleteReceipt(id: string) { if (!window.confirm('Delete this receipt permanently?')) return; setReceipts((current) => current.filter((receipt) => receipt.id !== id)); setSelectedReceipt(null); if (editingId === id) { setEditingId(null); setForm(blankForm('001')) } }
  function shareOnWhatsApp(receipt: Receipt) { const text = `MORYA GROUP%0AReceipt No. ${receipt.receiptNo}%0AHouse No. ${receipt.houseNo}%0AAmount: ${formatMoney(receipt.amount)}%0APayment: ${receipt.paymentMethod}%0ADate: ${formatDate(receipt.date)}`; window.open(`https://wa.me/?text=${text}`, '_blank', 'noopener,noreferrer') }

  return <main className="receipt-app">
    <div className="ganesh-loader" aria-hidden={!hydrated} data-hidden={hydrated}><img src={GANESH_IMAGE} alt="Shree Ganeshay Namah" /><p>|| श्री गणेशाय नमः ||</p><strong>MORYA GROUP</strong></div>
    <header className="topbar"><a className="brand-lockup" href="#overview"><div className="brand-mark"><img src={GANESH_IMAGE} alt="" /></div><div><p className="brand-name">MORYA GROUP</p><p className="brand-caption">Digital donation receipts</p></div></a><button className="mobile-menu" aria-label="Toggle menu" onClick={() => setMobileOpen((open) => !open)}><Menu /></button><nav className={mobileOpen ? 'top-nav is-open' : 'top-nav'} aria-label="Main navigation"><a className="active" href="#overview">Overview</a><a href="#history">Receipt history</a></nav></header>
    <div className="app-shell">
      <section className="page-heading" id="overview"><div><p className="eyebrow">|| जय गणेश ||</p><h1>Make every contribution count.</h1><p className="heading-copy">Create clear, respectful receipts for every Morya Group collection.</p></div><div className="heading-note"><span className="live-dot" /> Saved securely on this device</div></section>
      <section className="summary-grid" aria-label="Collection summary"><article className="summary-card summary-primary"><div className="summary-icon"><IndianRupee /></div><p>Today&apos;s amount</p><strong>{formatMoney(totals.today)}</strong><span>{totals.todayCount} receipt{totals.todayCount === 1 ? '' : 's'} today</span></article><article className="summary-card"><div className="summary-icon muted"><Sparkles /></div><p>Total collected</p><strong>{formatMoney(totals.total)}</strong><span>Across {totals.count} receipt{totals.count === 1 ? '' : 's'}</span></article><article className="summary-card summary-action"><div><p>Next step</p><strong>{editingId ? 'Update receipt' : 'Make a receipt'}</strong></div><a href="#new-receipt" aria-label="Go to receipt form"><ChevronRight /></a></article></section>
      <section className="workspace-grid"><form className="entry-card" id="new-receipt" onSubmit={saveReceipt} noValidate><div className="card-heading"><div><p className="eyebrow">{editingId ? 'Edit entry' : 'New entry'}</p><h2>{editingId ? 'Update receipt' : 'Create a receipt'}</h2></div><span className="required-note">* Required</span></div><div className="form-grid"><label className={errors.receiptNo ? 'field invalid' : 'field'}><span>Receipt number <em>*</em></span><input value={form.receiptNo} onChange={(event) => updateField('receiptNo', event.target.value)} placeholder="e.g. 001" aria-invalid={Boolean(errors.receiptNo)} />{errors.receiptNo && <small>{errors.receiptNo}</small>}</label><label className={errors.houseNo ? 'field invalid' : 'field'}><span>House / donor no. <em>*</em></span><input value={form.houseNo} onChange={(event) => updateField('houseNo', event.target.value)} placeholder="e.g. H-204" aria-invalid={Boolean(errors.houseNo)} />{errors.houseNo && <small>{errors.houseNo}</small>}</label><label className={errors.amount ? 'field invalid amount-field' : 'field amount-field'}><span>Amount <em>*</em></span><div className="amount-input"><span>Rs.</span><input type="number" min="1" step="0.01" value={form.amount} onChange={(event) => updateField('amount', event.target.value)} placeholder="0.00" aria-invalid={Boolean(errors.amount)} /></div>{errors.amount && <small>{errors.amount}</small>}</label><div className="field"><span>Payment method <em>*</em></span><div className="method-toggle" role="group" aria-label="Payment method"><button type="button" className={form.paymentMethod === 'Cash' ? 'selected' : ''} onClick={() => updateField('paymentMethod', 'Cash')}>Cash</button><button type="button" className={form.paymentMethod === 'Online' ? 'selected' : ''} onClick={() => updateField('paymentMethod', 'Online')}>Online</button></div></div><label className={errors.date ? 'field invalid' : 'field'}><span>Date <em>*</em></span><div className="date-input"><CalendarDays /><input type="date" value={form.date} onChange={(event) => updateField('date', event.target.value)} aria-invalid={Boolean(errors.date)} /></div>{errors.date && <small>{errors.date}</small>}</label></div><div className="form-footer"><p><Check /> Your receipt will be saved automatically.</p><div className="form-actions">{editingId && <button className="cancel-button" type="button" onClick={() => { setEditingId(null); setForm(blankForm('001')) }}>Cancel</button>}<button className="done-button" type="submit"><Plus data-icon="inline-start" /> {editingId ? 'Save changes' : 'Done & generate receipt'}</button></div></div></form><aside className="tip-card"><div className="tip-label">Morya Group</div><div className="tip-emblem"><img src={GANESH_IMAGE} alt="Morya emblem" /></div><h3>One seva. One shraddha. One Morya.</h3><p>Keep every contribution clear and ready to share with your donor.</p></aside></section>
      <section className="history-section" id="history"><div className="section-heading"><div><p className="eyebrow">Your records</p><h2>Recent receipts</h2></div><span className="receipt-count">{receipts.length} total</span></div>{receipts.length === 0 ? <div className="empty-state"><ReceiptText /><p>No receipts yet</p><span>Your saved receipts will appear here.</span></div> : <div className="receipt-list">{receipts.slice(0, 8).map((receipt) => <div className="receipt-row" key={receipt.id}><button className="receipt-row-main-button" onClick={() => setSelectedReceipt(receipt)}><span className="receipt-row-mark"><ReceiptText /></span><span className="receipt-row-main"><strong>Receipt #{receipt.receiptNo}</strong><small>House / donor {receipt.houseNo} · {formatDate(receipt.date)}</small></span><span className="payment-badge">{receipt.paymentMethod}</span><strong className="row-amount">{formatMoney(receipt.amount)}</strong></button><div className="row-actions"><button onClick={() => editReceipt(receipt)} aria-label={`Edit receipt ${receipt.receiptNo}`}><Edit3 /></button><button onClick={() => deleteReceipt(receipt.id)} aria-label={`Delete receipt ${receipt.receiptNo}`}><Trash2 /></button></div></div>)}</div>}</section>
    </div>
    {selectedReceipt && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelectedReceipt(null) }}><section className="receipt-modal" role="dialog" aria-modal="true" aria-labelledby="receipt-preview-title"><button className="close-modal" onClick={() => setSelectedReceipt(null)} aria-label="Close preview"><X /></button><div className="preview-paper" id="printable-receipt"><div className="preview-ornament">|| श्री गणेशाय नमः ||</div><div className="preview-brand"><div className="brand-mark"><img src={GANESH_IMAGE} alt="" /></div><div><strong>MORYA GROUP</strong><span>Digital donation receipt</span></div></div><div className="preview-title"><p>RECEIPT</p><strong>#{selectedReceipt.receiptNo}</strong></div><div className="preview-total"><span>Total paid</span><strong>{formatMoney(selectedReceipt.amount)}</strong></div><div className="preview-details"><div><span>House / donor no.</span><strong>{selectedReceipt.houseNo}</strong></div><div><span>Payment method</span><strong>{selectedReceipt.paymentMethod}</strong></div><div><span>Date issued</span><strong>{formatDate(selectedReceipt.date)}</strong></div></div><p className="preview-thanks">|| आपका सहयोग ||<br />Thank you for your contribution.</p></div><div className="modal-actions"><button className="outline-action" onClick={() => window.print()}><FileDown data-icon="inline-start" /> Download PDF</button><button className="edit-action" onClick={() => editReceipt(selectedReceipt)}><Edit3 data-icon="inline-start" /> Edit</button><button className="whatsapp-action" onClick={() => shareOnWhatsApp(selectedReceipt)}><MessageCircle data-icon="inline-start" /> Share on WhatsApp</button><button className="delete-action" onClick={() => deleteReceipt(selectedReceipt.id)}><Trash2 data-icon="inline-start" /> Delete</button></div></section></div>}
  </main>
}
